### ISSUE TITLE
Make shortcut configurable

### ISSUE THREAD

**Issue by TheCrazyT** [TheCrazyT/x64dbg-plugin-quickaccess#1]
Currently the shortcut is hardcoded.
Sadly the current source of x64dbg does not allow me to access the configuration instance.
(no suiteable dll exports ...)
As soon as x64dbg might allow that i should implement it inside the normal configuration.

There seems to be already an open issue about that:
https://github.com/x64dbg/x64dbg/issues/69

**Comment by mrexodia** [comment]
This feature has since been added to the x64dbg api. It tries the suggested shortcut and allows the user to change it in the shortcuts configuration window.

**Comment by TheCrazyT** [comment]
Hm my plugin is not listed there maybe because it has a submenu?

Oh well, that submenu actually gets generated by the plugin management of x64dbg.
The only shortcut i can change is the one of Scylla.
(still wonder why "Scylla" is listed as plugin, it seems to be installed by default and isn't inside the "plugins" directory)

**Comment by TheCrazyT** [comment]
Oh well i can of course just register a command and use the favorite-command window to assign a shortcut to it.
But i would say that is more a workaround (because you won't see the shortcut in the menu).
Gues thats what you was suggesting.

Edit:
Well i tried it with the current version.
For some reason it is still buggy.
If i do not execute through menu and just use the command it crashes.
If i use the menu and then use the command(or shortcut) everything is fine.

**Comment by mrexodia** [comment]
Hm weird, I’ll check it out then!

**Comment by TheCrazyT** [comment]
Currently I believe it has something to do with threading.
Maybe commands are runned from a different thread.
Problem is I can not even spawn my own thread (with QThread) because I read that all the window-stuff in Qt is single threaded.

Currently I'm_ clueless, I just guess I'm doing something completely wrong and accidently hijacking the applications main thread although I should use my own GUI-thread.
(so it worked with the old way "just by luck")

**Comment by TheCrazyT** [comment]
Alright i figured it out ... should have used events in first place ...

**Comment by mrexodia** [comment]
I'm checking the code and it seems like something is going a bit wrong there. Probably it's a good idea to redo the initialization/setup/stop logic based on the [QtPlugin](https://github.com/x64dbg/QtPlugin). Because right now when I tried `plugload quickaccess` and clicked the menu there was something going weird with the interface (a big white window opened and nothing was working).

Maybe it helps to explain a bit about the threading (see https://github.com/x64dbg/QtPlugin/blob/master/QtPlugin/pluginmain.cpp).

- `pluginit` can be executed on any thread (depending who is loading the plugin). From here you shouldn't do anything but initialize some global data, for example `pluginHandle` (see it like DllMain).
- `plugsetup` can also be executed on any thread, so that's why you use `GuiExecuteOnGuiThread` to force your Qt initialization (and timers etc) to execute on the GUI thread (Qt message loop thread). There is `QtPlugin::WaitForSetup();` which is waiting for your code to be executed.
- `plugstop` can also be executed on any thread, so there is also `GuiExecuteOnGuiThread` and `QtPlugin::WaitForStop();`

If you do it this way you can use Qt pretty much like normal, only you should use a signal to for example do the interaction between the x64dbg menus and your menus, but the menu signals are already executed on the GUI thread so it will be the same as a direct call in most cases.

You can also check https://github.com/x64dbg/snowman/blob/x64dbg-module/src/x64dbg-module/QtPlugin.cpp for a more elaborate Qt plugin if you're interested.
